Merge

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
dframeo = DataFrame({'key':['X','Z','I','A','P','H'],'data_set_1':np.arange(6)})
dframeo

data_set_1 key
0           0   X
1           1   Z
2           2   I
3           3   A
4           4   P
5           5   H

In [3]:
dframer = DataFrame({'key':['Q','T','P'],'data_set_2':[1,2,3]})
dframer

data_set_2 key
0           1   Q
1           2   T
2           3   P

In [4]:
pd.merge(dframeo,dframer)

data_set_1 key  data_set_2
0           4   P           3

In [5]:
pd.merge(dframeo,dframer,on='key')

data_set_1 key  data_set_2
0           4   P           3

In [6]:
pd.merge(dframeo,dframer,on='key',how='left')

data_set_1 key  data_set_2
0           0   X         NaN
1           1   Z         NaN
2           2   I         NaN
3           3   A         NaN
4           4   P         3.0
5           5   H         NaN

In [7]:
dframer

data_set_2 key
0           1   Q
1           2   T
2           3   P

In [9]:
pd.merge(dframeo,dframer,on='key',how='right')

data_set_1 key  data_set_2
0         4.0   P           3
1         NaN   Q           1
2         NaN   T           2

In [10]:
pd.merge(dframeo,dframer,on='key',how='outer')

data_set_1 key  data_set_2
0         0.0   X         NaN
1         1.0   Z         NaN
2         2.0   I         NaN
3         3.0   A         NaN
4         4.0   P         3.0
5         5.0   H         NaN
6         NaN   Q         1.0
7         NaN   T         2.0

In [11]:
dframec = DataFrame({'key':['X','X','D','W','Z','A'],'data_set_3':range(6)})
dframec

data_set_3 key
0           0   X
1           1   X
2           2   D
3           3   W
4           4   Z
5           5   A

In [13]:
dframet = DataFrame({'key':['Y','W','X','X','A'],'data_set_4':range(5)})
dframet

data_set_4 key
0           0   Y
1           1   W
2           2   X
3           3   X
4           4   A

In [14]:
pd.merge(dframec,dframet)

data_set_3 key  data_set_4
0           0   X           2
1           0   X           3
2           1   X           2
3           1   X           3
4           3   W           1
5           5   A           4

In [15]:
pd.merge(dframec,dframet,on='key',how='left')

data_set_3 key  data_set_4
0           0   X         2.0
1           0   X         3.0
2           1   X         2.0
3           1   X         3.0
4           2   D         NaN
5           3   W         1.0
6           4   Z         NaN
7           5   A         4.0

In [16]:
df_left = DataFrame({'key_1':['SD','SF','LA'],'key_2':['one','two','one'],'left_data':[12,14,16]})

In [17]:
dr_right = DataFrame({'key_1':['SD','SF','LA','SF'],'key_2':['one','one','one','two'],'right_data':[40,13,56,78]})

In [18]:
df_left

key_1 key_2  left_data
0    SD   one         12
1    SF   two         14
2    LA   one         16

In [20]:
dr_right

key_1 key_2  right_data
0    SD   one          40
1    SF   one          13
2    LA   one          56
3    SF   two          78

In [21]:
pd.merge(df_left,dr_right,on=['key_1','key_2'],how='outer')

key_1 key_2  left_data  right_data
0    SD   one       12.0          40
1    SF   two       14.0          78
2    LA   one       16.0          56
3    SF   one        NaN          13

In [22]:
pd.merge(df_left,dr_right,on='key_1')

key_1 key_2_x  left_data key_2_y  right_data
0    SD     one         12     one          40
1    SF     two         14     one          13
2    SF     two         14     two          78
3    LA     one         16     one          56

In [24]:
pd.merge(df_left,dr_right,on='key_1',suffixes=('_lefty','_righty'))

key_1 key_2_lefty  left_data key_2_righty  right_data
0    SD         one         12          one          40
1    SF         two         14          one          13
2    SF         two         14          two          78
3    LA         one         16          one          56

url z pliku

Merge on index

In [25]:
df_leftt = DataFrame({'key':['X','U','Z','X','Z'],'data':range(5)})

In [26]:
df_leftt

data key
0     0   X
1     1   U
2     2   Z
3     3   X
4     4   Z

In [27]:
df_rightt = DataFrame({'gropu_data':[10,20]},index=['X','U'])
df_rightt

gropu_data
X          10
U          20

In [28]:
pd.merge(df_leftt,df_rightt,left_on='key',right_index=True)

data key  gropu_data
0     0   X          10
3     3   X          10
1     1   U          20

In [31]:
df_left_HR = DataFrame({'KEY_1':['SD','HJ','LA','LA','HJ'],'KEY2':[10,20,10,30,21],'dataset':np.arange(5.)})
df_left_HR

KEY2 KEY_1  dataset
0    10    SD      0.0
1    20    HJ      1.0
2    10    LA      2.0
3    30    LA      3.0
4    21    HJ      4.0

In [33]:
df_right_HR = DataFrame(np.arange(10).reshape(5,2),index=[['LA','SD','HJ','SD','LA'],[20,10,34,10,31]],columns=['col1','col2'])

In [34]:
df_right_HR

col1  col2
LA 20     0     1
SD 10     2     3
HJ 34     4     5
SD 10     6     7
LA 31     8     9

In [35]:
df_right_HR = DataFrame(np.arange(10).reshape(5,2),index=[['SD','SD','HJ','HJ','HJ'],[20,10,34,10,31]],columns=['col1','col2'])

In [36]:
df_right_HR

col1  col2
SD 20     0     1
   10     2     3
HJ 34     4     5
   10     6     7
   31     8     9

In [37]:
pd.merge(df_left_HR,df_right_HR,left_on=['KEY_1','KEY2'],right_index=True)

KEY2 KEY_1  dataset  col1  col2
0    10    SD      0.0     2     3

In [38]:
df_left_HR.join(df_right_HR)

ValueError: cannot join with no overlapping index names

In [39]:
df_leftt.join(df_rightt)

data key  gropu_data
0     0   X         NaN
1     1   U         NaN
2     2   Z         NaN
3     3   X         NaN
4     4   Z         NaN

Concatenate

In [41]:
arr10 = np.arange(16).reshape(4,4)

arr10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
np.concatenate([arr10,arr10],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15]])

In [43]:
np.concatenate([arr10,arr10],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
seer1 = Series([0,1,3],index=['T','O','P'])
seer2 = Series([5,6],index=['X','Z'])

In [45]:
seer1

T    0
O    1
P    3
dtype: int64

In [46]:
seer2

X    5
Z    6
dtype: int64

In [47]:
pd.concat([seer1,seer2])

T    0
O    1
P    3
X    5
Z    6
dtype: int64

In [48]:
pd.concat([seer1,seer2],axis=0)

T    0
O    1
P    3
X    5
Z    6
dtype: int64

In [49]:
pd.concat([seer1,seer2],axis=1)

C:\Users\DamianAleksanderMiko\Anaconda3\envs\testenv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
O  1.0  NaN
P  3.0  NaN
T  0.0  NaN
X  NaN  5.0
Z  NaN  6.0

In [50]:
pd.concat([seer1,seer2],keys=['cat1','cat2'])

cat1  T    0
      O    1
      P    3
cat2  X    5
      Z    6
dtype: int64

In [51]:
dframe1 = DataFrame(np.random.randn(4,5),columns=['X','A','B','Q','P'])

In [52]:
dframe2 = DataFrame(np.random.randn(3,5),columns=['A','B','X','Q','P'])

In [53]:
dframe1

X         A         B         Q         P
0  0.919492 -0.423728 -0.324182  0.651131  1.292622
1  0.670972 -0.053409 -0.808962  0.912487 -1.659900
2 -1.522234  0.510661 -0.260471 -0.229130 -0.340432
3  0.673200  0.752383  0.398188  0.505164  0.000329

In [54]:
dframe2

A         B         X         Q         P
0  1.436875  0.065870 -0.078190  0.192028  1.152734
1  0.115506 -0.329115 -0.704959 -1.468336  1.294474
2  0.293378  1.397597 -0.408093 -0.445642  1.567927

In [55]:
pd.concat([dframe1,dframe2])

C:\Users\DamianAleksanderMiko\Anaconda3\envs\testenv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A         B         P         Q         X
0 -0.423728 -0.324182  1.292622  0.651131  0.919492
1 -0.053409 -0.808962 -1.659900  0.912487  0.670972
2  0.510661 -0.260471 -0.340432 -0.229130 -1.522234
3  0.752383  0.398188  0.000329  0.505164  0.673200
0  1.436875  0.065870  1.152734  0.192028 -0.078190
1  0.115506 -0.329115  1.294474 -1.468336 -0.704959
2  0.293378  1.397597  1.567927 -0.445642 -0.408093

Jeżeli czegoś nie ma w bazie to NaN

In [56]:
pd.concat([dframe1,dframe2],ignore_index=True)

C:\Users\DamianAleksanderMiko\Anaconda3\envs\testenv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A         B         P         Q         X
0 -0.423728 -0.324182  1.292622  0.651131  0.919492
1 -0.053409 -0.808962 -1.659900  0.912487  0.670972
2  0.510661 -0.260471 -0.340432 -0.229130 -1.522234
3  0.752383  0.398188  0.000329  0.505164  0.673200
4  1.436875  0.065870  1.152734  0.192028 -0.078190
5  0.115506 -0.329115  1.294474 -1.468336 -0.704959
6  0.293378  1.397597  1.567927 -0.445642 -0.408093

url w pliku

Combining DataFrames

In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
ser0 = Series([2,np.nan,4,np.nan,6,np.nan,7],index=['Q','W','T','A','V','K','P'])
ser0

Q    2.0
W    NaN
T    4.0
A    NaN
V    6.0
K    NaN
P    7.0
dtype: float64

In [3]:
ser3 = Series(np.arange(len(ser0)),dtype=np.float64,
             index=['Q','W','T','A','V','K','P'])
ser3

Q    0.0
W    1.0
T    2.0
A    3.0
V    4.0
K    5.0
P    6.0
dtype: float64

In [4]:
Series(np.where(pd.isnull(ser0),ser3,ser0),index=ser0.index)

Q    2.0
W    1.0
T    4.0
A    3.0
V    6.0
K    5.0
P    7.0
dtype: float64

In [5]:
ser0.combine_first(ser3)

Q    2.0
W    1.0
T    4.0
A    3.0
V    6.0
K    5.0
P    7.0
dtype: float64

In [6]:
nan=np.nan
dframe_odddds = DataFrame({'S':[1.,nan,3.,nan],
                          'O':[nan,5.,nan,9.],
                          'I':[nan,8.,nan,4.]})

In [7]:
dframe_evens = DataFrame({'S':[2.,4.,nan,6.,8.],
                         'O':[nan,10.,12.,14.,16.]})

In [8]:
dframe_evens

O    S
0   NaN  2.0
1  10.0  4.0
2  12.0  NaN
3  14.0  6.0
4  16.0  8.0

In [10]:
dframe_odddds

I    O    S
0  NaN  NaN  1.0
1  8.0  5.0  NaN
2  NaN  NaN  3.0
3  4.0  9.0  NaN

In [11]:
dframe_odddds.combine_first(dframe_evens)

I     O    S
0  NaN   NaN  1.0
1  8.0   5.0  4.0
2  NaN  12.0  3.0
3  4.0   9.0  6.0
4  NaN  16.0  8.0

Reshaping

In [12]:
dframe8 = DataFrame(np.arange(16).reshape(2,8),
                   index=pd.Index(['La','SF'],name='city'),
                   columns=pd.Index(['A','B','C','D','E','F','G','H']))
dframe8

A  B   C   D   E   F   G   H
city                              
La    0  1   2   3   4   5   6   7
SF    8  9  10  11  12  13  14  15

In [13]:
dframe_st = dframe8.stack()
dframe_st

city   
La    A     0
      B     1
      C     2
      D     3
      E     4
      F     5
      G     6
      H     7
SF    A     8
      B     9
      C    10
      D    11
      E    12
      F    13
      G    14
      H    15
dtype: int32

In [14]:
dframe_st.unstack()

A  B   C   D   E   F   G   H
city                              
La    0  1   2   3   4   5   6   7
SF    8  9  10  11  12  13  14  15

In [15]:
dframe_st.unstack('city')

city  La  SF
A      0   8
B      1   9
C      2  10
D      3  11
E      4  12
F      5  13
G      6  14
H      7  15

In [16]:
ser1 = Series([0,1,2,3],index=['Q','X','U','O'])
ser4 = Series([4,5,6],index=['X','Y','Z'])

In [17]:
dframe = pd.concat([ser1,ser4],keys=['Alpha','Beta'])
dframe

Alpha  Q    0
       X    1
       U    2
       O    3
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [19]:
dframe.unstack()

O    Q    U    X    Y    Z
Alpha  3.0  0.0  2.0  1.0  NaN  NaN
Beta   NaN  NaN  NaN  4.0  5.0  6.0

In [21]:
dframe.unstack().stack()

Alpha  O    3.0
       Q    0.0
       U    2.0
       X    1.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [22]:
dframe = dframe.unstack()

In [23]:
dframe

O    Q    U    X    Y    Z
Alpha  3.0  0.0  2.0  1.0  NaN  NaN
Beta   NaN  NaN  NaN  4.0  5.0  6.0

In [25]:
dframe.stack()

Alpha  O    3.0
       Q    0.0
       U    2.0
       X    1.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

Pivoting

In [26]:
# Lets create some data to play with:

# Note: It is not necessary to understand how this dataset was made to understand this Lecture.

#import pandas testing utility
import pandas.util.testing as tm; tm.N = 3

#Create a unpivoted function
def unpivot(frame):
    N, K = frame.shape
    
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    
    # Return the DataFrame
    return DataFrame(data, columns=['date', 'variable', 'value'])

#Set the DataFrame we'll be using
dframe = unpivot(tm.makeTimeDataFrame())
dframe

date variable     value
0  2000-01-03        A -0.342469
1  2000-01-04        A -0.602126
2  2000-01-05        A -0.134989
3  2000-01-03        B  1.592473
4  2000-01-04        B  1.084750
5  2000-01-05        B  0.875923
6  2000-01-03        C  0.158556
7  2000-01-04        C  0.297160
8  2000-01-05        C -0.555308
9  2000-01-03        D  0.668329
10 2000-01-04        D  1.071831
11 2000-01-05        D  1.750622

In [27]:
dframe_piv = dframe.pivot('date','variable','value')
dframe_piv

variable           A         B         C         D
date                                              
2000-01-03 -0.342469  1.592473  0.158556  0.668329
2000-01-04 -0.602126  1.084750  0.297160  1.071831
2000-01-05 -0.134989  0.875923 -0.555308  1.750622

Duplicates in DataFrames

In [28]:
dframe4 = DataFrame({'key1':['A']*2 + ['N']*3,
                   'key2':[2,2,3,3,3]})
dframe4

key1  key2
0    A     2
1    A     2
2    N     3
3    N     3
4    N     3

In [29]:
dframe.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [30]:
dframe.drop_duplicates()

date variable     value
0  2000-01-03        A -0.342469
1  2000-01-04        A -0.602126
2  2000-01-05        A -0.134989
3  2000-01-03        B  1.592473
4  2000-01-04        B  1.084750
5  2000-01-05        B  0.875923
6  2000-01-03        C  0.158556
7  2000-01-04        C  0.297160
8  2000-01-05        C -0.555308
9  2000-01-03        D  0.668329
10 2000-01-04        D  1.071831
11 2000-01-05        D  1.750622

In [31]:
dframe4.duplicated()

0    False
1     True
2    False
3     True
4     True
dtype: bool

In [32]:
dframe4.drop_duplicates()

key1  key2
0    A     2
2    N     3

In [34]:
dframe4.drop_duplicates(['key1'])

key1  key2
0    A     2
2    N     3

In [35]:
dframe4

key1  key2
0    A     2
1    A     2
2    N     3
3    N     3
4    N     3

In [42]:
dframe4.drop_duplicates(['key1'],keep=False)

Empty DataFrame
Columns: [key1, key2]
Index: []

In [43]:
dframe4.drop_duplicates(['key1'],keep=False)

Empty DataFrame
Columns: [key1, key2]
Index: []

take_last=True ??

Mapping

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
dframe = DataFrame({'City':['Brain Head','Alma','Fox Park'],
                   'altitude':[3168,5533,3122]})
dframe

City  altitude
0  Brain Head      3168
1        Alma      5533
2    Fox Park      3122

In [3]:
state_map = {'Alma':'Colorado','Brain Head':'Utah','Fox Park':'Wyoming'}

In [6]:
dframe['state'] = dframe['City'].map(state_map)

In [7]:
dframe

City  altitude     state
0  Brain Head      3168      Utah
1        Alma      5533  Colorado
2    Fox Park      3122   Wyoming

Replace

In [8]:
sr = Series([1,2,3,4,1,2,3,4])
sr

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [9]:
sr.replace(1,np.nan)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [10]:
sr.replace([1,4],[100,234])

0    100
1      2
2      3
3    234
4    100
5      2
6      3
7    234
dtype: int64

In [11]:
sr.replace({4:np.nan})

0    1.0
1    2.0
2    3.0
3    NaN
4    1.0
5    2.0
6    3.0
7    NaN
dtype: float64

Rename index

In [12]:
dframme = DataFrame(np.arange(16).reshape(4,4),index=['N','Y','L','A'],columns=['A','B','C','D'])
dframme

A   B   C   D
N   0   1   2   3
Y   4   5   6   7
L   8   9  10  11
A  12  13  14  15

In [13]:
dframme.index.map(str.lower)

Index([u'n', u'y', u'l', u'a'], dtype='object')

In [14]:
dframme.index = dframme.index.map(str.lower)
dframme

A   B   C   D
n   0   1   2   3
y   4   5   6   7
l   8   9  10  11
a  12  13  14  15

In [22]:
dframme.rename(index=str.lower,columns=str.lower)

a   b   c   d
n   0   1   2   3
y   4   5   6   7
l   8   9  10  11
a  12  13  14  15

str.title, str.lower nie działają 

In [21]:
dframme.rename(index=str.title, columns=str.lower)

a   b   c   d
N   0   1   2   3
Y   4   5   6   7
L   8   9  10  11
A  12  13  14  15

In [24]:
dframme.rename(index={'ny':'NEW YORK'},
             columns={'A':'ALPHA'})

ALPHA   B   C   D
n      0   1   2   3
y      4   5   6   7
l      8   9  10  11
a     12  13  14  15

In [25]:
dframe

City  altitude     state
0  Brain Head      3168      Utah
1        Alma      5533  Colorado
2    Fox Park      3122   Wyoming

In [26]:
dframme.rename(index={'n':'NEW YORK'},inplace=True)
dframme

A   B   C   D
NEW YORK   0   1   2   3
y          4   5   6   7
l          8   9  10  11
a         12  13  14  15

Binning

In [27]:
years = [1990,1998,1992,2008,2019,2001,1671,1776,1410]

In [28]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]

In [29]:
decade_cat = pd.cut(years,decade_bins)

In [30]:
decade_cat

[(1980.0, 1990.0], (1990.0, 2000.0], (1990.0, 2000.0], (2000.0, 2010.0], (2010.0, 2020.0], (2000.0, 2010.0], NaN, NaN, NaN]
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [31]:
decade_cat.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]],
              closed='right',
              dtype='interval[int64]')

In [32]:
pd.value_counts(decade_cat)

(2000, 2010]    2
(1990, 2000]    2
(2010, 2020]    1
(1980, 1990]    1
(1970, 1980]    0
(1960, 1970]    0
dtype: int64

In [34]:
pd.cut(years,2,precision=1)

[(1714.5, 2019.0], (1714.5, 2019.0], (1714.5, 2019.0], (1714.5, 2019.0], (1714.5, 2019.0], (1714.5, 2019.0], (1409.4, 1714.5], (1714.5, 2019.0], (1409.4, 1714.5]]
Categories (2, interval[float64]): [(1409.4, 1714.5] < (1714.5, 2019.0]]

Outliers

In [35]:
np.random.seed(12345)

In [37]:
dframe = DataFrame(np.random.randn(1000,4))

In [38]:
dframe.head()

0         1         2         3
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  0.274992  0.228913  1.352917  0.886429
4 -2.001637 -0.371843  1.669025 -0.438570

In [39]:
dframe.tail()

0         1         2         3
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

In [40]:
dframe.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [41]:
col = dframe[0]

In [42]:
col.head()

0   -0.204708
1    1.965781
2    0.769023
3    0.274992
4   -2.001637
Name: 0, dtype: float64

In [43]:
col[np.abs(col)>3]

523   -3.428254
900    3.366626
Name: 0, dtype: float64

In [44]:
dframe[(np.abs(dframe)>3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [45]:
dframe[np.abs(dframe)>3] = np.sign(dframe)*3

abs = absolute value

In [46]:
dframe.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

HOW 

Permutation

In [47]:
dfem = DataFrame(np.arange(20).reshape(4,5))

In [48]:
blender =np.random.permutation(4)

In [49]:
blender

array([1, 3, 2, 0])

In [50]:
dfem

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [51]:
dframe.take(blender)

0         1         2         3
1  1.965781  1.393406  0.092908  0.281746
3  0.274992  0.228913  1.352917  0.886429
2  0.769023  1.246435  1.007189 -1.296221
0 -0.204708  0.478943 -0.519439 -0.555730

not this

In [52]:
dfem.take(blender)

0   1   2   3   4
1   5   6   7   8   9
3  15  16  17  18  19
2  10  11  12  13  14
0   0   1   2   3   4

In [53]:
box = np.array([1,2,3])

In [54]:
shaker = np.random.randint(0,len(box),size=10)

In [55]:
shaker

array([2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [56]:
hand_grabs = box.take(shaker)

In [57]:
hand_grabs

array([3, 1, 3, 1, 3, 1, 3, 1, 3, 3])